### ISSUE TITLE
 it's working?

### ISSUE THREAD

**Issue by misaelzinho** [ROFLailXGOD/twitch-farmer#3] opened 2020-12-15 19:42 UTC
I tried to use but keeps giving this error
![image](https://user-images.githubusercontent.com/74842818/102264511-850b8880-3ef4-11eb-965f-c8d97cba01cb.png)

**Comment by ROFLailXGOD** [comment] 2020-12-15 19:49
It surely was like 2 weeks ago. Are you sure you renamed `settings/local.py.skeleton` to `settings/local.py` and replaced all of the values?

**Comment by misaelzinho** [comment] 2020-12-16 14:53
yes 
![image](https://user-images.githubusercontent.com/74842818/102364530-52659c80-3f95-11eb-945c-4e30ccf6f971.png)

**Comment by ROFLailXGOD** [comment] 2020-12-16 15:01
Oh, I see the problem. Remove `bearer` from the value:

```
BEARER = 'jvu70...'
```

**Comment by misaelzinho** [comment] 2020-12-16 15:03
Worked, thank you

**Comment by misaelzinho** [comment] 2020-12-16 15:04
Can I use it on a vps?

**Comment by ROFLailXGOD** [comment] 2020-12-16 15:08
In theory yes, but tests showed that it can't really work for prolonged periods of time (like for days). No idea what the problem is, but don't really care either, because it's enough to get all the new emotes. You may try, though, maybe you'll be luckier.

I'm going to close this issue, but if you have any other questions, feel free to ask.

**Closed as completed by ROFLailXGOD** 2020-12-16 15:08 UTC
