### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by iknowew** [ROFLailXGOD/twitch-farmer#9] opened 2021-05-22 00:21 UTC
It's not working, it's just generating error logs for me. I haven't figured out what it is yet.

File "C:\Users\East\Documents\twitch-farmer\app.py", line 25, in <module>
    asyncio.run(run())
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\East\Documents\twitch-farmer\app.py", line 18, in run
    await asyncio.gather(
  File "C:\Users\East\Documents\twitch-farmer\sources\new_api.py", line 101, in idle
    streamers = await get_active_streams(session)
  File "C:\Users\East\Documents\twitch-farmer\sources\new_api.py", line 71, in get_active_streams
    for stream in streams['data']
KeyError: 'data'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002364EBC1550>
Traceback (most recent call last):
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002364EBC1550>
Traceback (most recent call last):
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

**Comment by ROFLailXGOD** [comment] 2021-05-22 00:31
Looks like you didn't get a response from twitch. Something might be wrong with credentials or settings in general. I guess you can try to insert `print(streams)` after [this](https://github.com/ROFLailXGOD/twitch-farmer/blob/master/sources/new_api.py#L68) line and see what you have.

**Comment by iknowew** [comment] 2021-05-22 00:57
I received this answer on cmd: [WinError 64] The specified network name is no longer available

**Comment by iknowew** [comment] 2021-05-22 01:47
I tried it in several ways, I got the client id through the website https://twitchtokengenerator.com/, I tried it through the twitch dev console, I got several oauth token and I still didn't get it. show me some different errors, when the token changes it shows that it was not authorized by the token, but I think that maybe the token is not the problem.

Traceback (most recent call last):
  File "C:/Users/East/Documents/your_directory/app.py", line 25, in <module>
    asyncio.run(run())
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/East/Documents/your_directory/app.py", line 15, in run
    reader, writer = await asyncio.open_connection(HOST, PORT)
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\East\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

Process finished with exit code 1

**Comment by ROFLailXGOD** [comment] 2021-05-25 22:50
I personally have never tried using https://twitchtokengenerator.com/, so I can't answer if the token from there is valid or not. I suggest you to follow the instructions that I just verified once again:

1. Go [here](https://twitchapps.com/tmi/) and get your `OAUTH` token
2. Go [there](https://dev.twitch.tv/console/apps) and register an app. Don't forget to specify https://twitchapps.com/tokengen/ in "OAuth Redirect URLs". That'll give you a `CLIENT_ID`
3. Go [here](https://twitchapps.com/tokengen/) and specify your `CLIENT_ID`. It'll generate `BEARER` token for you

After all of this you should no longer get errors with authentification. Keep in mind that you'll need to generete a new `BEARER` token from time to time, because the old one expires with time. Other 2 should not expire at all.

Tell me if that helped.

**Comment by ROFLailXGOD** [comment] 2021-06-30 08:58
Since it's been more than a month and I've confirmed that the application still works, I'm closing the issue for now. Feel free to reopen it, if needed.

**Closed as completed by ROFLailXGOD** 2021-06-30 08:58 UTC

**Comment by phil330d** [comment] 2021-08-24 16:18
Got the same Error (WinError 64), just went through the steps creating the tokens again, and it works now, for anyone else encountering this problem.
